//Initial code generated by Gemini Enterprise 2026-03-27
using System;
using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Interop;

public static class WindowFlasher
{
    private const uint FLASHW_STOP = 0; // Stop flashing. The system restores the window to its original state.
    private const uint FLASHW_CAPTION = 1; // Flash the window caption.
    private const uint FLASHW_TRAY = 2; // Flash the taskbar button.
    private const uint FLASHW_ALL = 3; // Flash both the window caption and taskbar button.
    private const uint FLASHW_TIMER = 4; // Flash continuously, until the FLASHW_STOP flag is set.
    private const uint FLASHW_TIMERNOFG = 12; // Flash continuously until the window comes to the foreground.

    [StructLayout(LayoutKind.Sequential)]
    private struct FLASHWINFO
    {
        public uint cbSize;
        public IntPtr hwnd;
        public uint dwFlags;
        public uint uCount;
        public uint dwTimeout;
    }

    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static extern bool FlashWindowEx(ref FLASHWINFO pwfi);

    /// <summary>
    /// Flashes the window's taskbar icon.
    /// </summary>
    /// <param name="window">The window to flash.</param>
    /// <param name="count">The number of times to flash. If 0, it flashes indefinitely.</param>
    public static void Flash(Window window, uint count = 5)
    {
        if (window.IsActive) return;

        WindowInteropHelper wih = new WindowInteropHelper(window);
        FLASHWINFO info = new FLASHWINFO
        {
            hwnd = wih.Handle,
            dwFlags = FLASHW_ALL | (count == 0 ? FLASHW_TIMER : 0),
            uCount = count,
            dwTimeout = 0
        };
        info.cbSize = Convert.ToUInt32(Marshal.SizeOf(info));
        FlashWindowEx(ref info);
    }

    /// <summary>
    /// Stops flashing the window's taskbar icon.
    /// </summary>
    /// <param name="window">The window to stop flashing.</param>
    public static void StopFlashing(Window window)
    {
        WindowInteropHelper wih = new WindowInteropHelper(window);
        FLASHWINFO info = new FLASHWINFO();
        info.hwnd = wih.Handle;
        info.cbSize = Convert.ToUInt32(Marshal.SizeOf(info));
        info.dwFlags = FLASHW_STOP;
        FlashWindowEx(ref info);
    }
}
